source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use postgresql as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'active_model_serializers'
gem 'acts-as-taggable-on'
gem 'acts_as_votable', '~> 0.8.0'
gem 'devise', '~> 3.0.0.rc'
gem 'omniauth-facebook', '1.4.0'
gem 'cancan'
gem 'acts_as_commentable'
gem 'rails-timeago', '~> 2.0'
gem 'angularjs-rails'
gem 'rails_admin'
#gem 'mongo'
gem 'simple_form'
gem 'bson_ext'
gem 'json'
gem 'htmlentities'

#gem 'activeadmin', github: 'gregbell/active_admin'

gem 'twitter-text', github: 'twitter/twitter-text-rb'
gem 'twitter'

#image processing in the coud
gem 'carrierwave'
gem 'cloudinary'




#heroku dependency
gem 'rails_12factor', group: :production

ruby "1.9.3"

