# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b21d1dd10eab2423f4814bf30f63776db52f551a2ede0d3a6739176f1a53217990bcc9ffe38bb9a901c717f8ed7f752d9543f49a6f509aedca667d3a9048ce

test:
  secret_key_base: aa48ad7c546f1f90e73accb34079fd1fbba85ac3304b7c8a6c1e921b6c0a7a1192556b80cad7fbc95f07fe5610b6d07654c50b3922a6316353f597606e84748f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
